import assert from 'node:assert/strict';
import {buildPlan,normalizeAddress} from '../src/core.js';
const property={zoningDistrict:'R3',historicDistrict:null,floodplain:null,conservationPotential:false,historicExteriorReview:false,openPermitsUnknown:true};
assert.equal(normalizeAddress(' 130 Wheeler Road, MA 02459 '),'130 Wheeler Road');
let p=buildPlan('basement_finish',property,{sleepingRoomAdded:true,bathroomAdded:true,electricalWork:true,plumbingWork:true,gasWork:false,exteriorExpansion:false});
assert.ok(p.results.some(x=>x.id==='project.electrical'&&x.status==='required'));
assert.ok(p.results.some(x=>x.id==='project.plumbing'&&x.status==='required'));
assert.ok(p.results.some(x=>x.id==='basement.egress'&&x.status==='needs_confirmation'));
assert.ok(p.results.some(x=>x.id==='workflow.open-permits'&&x.status==='needs_confirmation'));
p=buildPlan('addition',{...property,historicDistrict:'Example District',historicExteriorReview:true,floodplain:'Flood Zone',conservationPotential:true},{newArea:500,stories:1,structuralChanges:true,electricalWork:true,plumbingWork:false,gasWork:false});
assert.ok(p.results.some(x=>x.id==='project.far'));
assert.ok(p.results.some(x=>x.id==='project.tree'));
assert.ok(p.results.some(x=>x.id==='property.historic'));
assert.ok(p.results.some(x=>x.id==='project.conservation'));
console.log('core MVP regression tests: PASS');