import assert from 'node:assert/strict';
import {buildPlan} from '../src/core.js';
const base={zoningDistrict:'R3',historicDistrict:null,floodplain:null,conservationPotential:false,historicExteriorReview:false,openPermitsUnknown:true};
let count=0; const cases=[];
for(const sleeping of [false,true]) for(const bath of [false,true]) for(const elec of [false,true]) for(const plumbing of [false,true]) for(const gas of [false,true]) cases.push({type:'basement_finish',property:base,a:{sleepingRoomAdded:sleeping,bathroomAdded:bath,electricalWork:elec,plumbingWork:plumbing,gasWork:gas,exteriorExpansion:false}});
for(const elec of [false,true]) for(const plumbing of [false,true]) for(const structural of [false,true]) for(const vent of [false,true]) cases.push({type:'bathroom_renovation',property:base,a:{electricalWork:elec,plumbingWork:plumbing,structuralChanges:structural,newVentilation:vent}});
for(const historic of [null,'District']) for(const flood of [null,'Flood Zone']) for(const elec of [false,true]) for(const structural of [false,true]) {const property={...base,historicDistrict:historic,historicExteriorReview:Boolean(historic),floodplain:flood,conservationPotential:Boolean(flood)};cases.push({type:'addition',property,a:{newArea:500,stories:1,electricalWork:elec,plumbingWork:false,gasWork:false,structuralChanges:structural}});}
assert.ok(cases.length>=50);
for(const c of cases){const p=buildPlan(c.type,c.property,c.a);count++;for(const r of p.results){assert.ok(['required','potentially_required','needs_confirmation','not_applicable'].includes(r.status),r.id);assert.ok(Array.isArray(r.sources)&&r.sources.length>0,`missing provenance ${r.id}`);if(r.status==='needs_confirmation')assert.doesNotMatch(r.action,/definitely|compliant|approved/i);}if(c.type==='basement_finish'&&c.a.sleepingRoomAdded)assert.ok(p.results.some(r=>r.id==='basement.egress'&&r.status==='needs_confirmation'));if(c.type==='addition')assert.ok(p.results.some(r=>r.id==='project.far'));if(c.type==='addition'&&c.property.historicDistrict)assert.ok(p.results.some(r=>r.id==='property.historic'));if(c.type==='addition'&&!c.property.historicDistrict)assert.ok(!p.results.some(r=>r.id==='property.historic'));}
console.log('reliability regression tests: PASS ('+count+' scenarios)');