import assert from 'node:assert/strict';
import {normalizeHtml,normalizeText,sha256,meaningfulDiff,classifyChange,safetyAssessment} from '../index.mjs';
import fs from 'node:fs';
const map=JSON.parse(fs.readFileSync(new URL('../config/knowledge-map.json',import.meta.url)));
const sources=JSON.parse(fs.readFileSync(new URL('../config/sources.json',import.meta.url)));
assert.ok(map.mappings.length>0);
assert.ok(map.mappings.every(m=>Array.isArray(m.ruleIds)&&Array.isArray(m.projectTypes)&&Array.isArray(m.questionIds)));
assert.ok(new Set(map.mappings.map(m=>m.sourceId)).size===map.mappings.length);
assert.ok(map.mappings.every(m=>sources.some(s=>s.id===m.sourceId)));
const a='<header>Menu</header><main><h1>Permit</h1><p>Permit is required.</p></main><footer>Cookie</footer><script>x()</script>';
const b='<header>Other menu</header><main><h1>Permit</h1><p>Permit is required.</p></main><footer>Other</footer>';
assert.equal(normalizeHtml(a),normalizeHtml(b));
assert.equal(normalizeText(' a  b\n\n\nc '),'a b\n\nc');
const prev={hash:sha256('Permit required.'),text:'Permit required.'};
assert.equal(meaningfulDiff(prev,{hash:prev.hash,text:prev.text}).changed,false);
const changed={hash:sha256('Permit required. Setback is 10 ft.'),text:'Permit required. Setback is 10 ft.'};
assert.equal(meaningfulDiff(prev,changed).changed,true);
const source={monitoring:{authorityTier:'primary',topics:['setback','permit']}};
assert.equal(classifyChange(source,{changed:false,added:[],removed:[]}),'A_NO_MEANINGFUL_CHANGE');
assert.equal(classifyChange(source,{changed:true,added:['Navigation only'],removed:[]}),'C_INFORMATIONAL_IRRELEVANT_TO_HPP');
assert.equal(classifyChange(source,{changed:true,added:['Setback requirement changed from 10 ft to 8 ft'],removed:[]}),'E_POTENTIALLY_REGULATORY_CHANGE');
const safety=safetyAssessment(source,'E_POTENTIALLY_REGULATORY_CHANGE',{ruleIds:['project.far']});
assert.equal(safety.decision,'HUMAN_REVIEW'); assert.equal(safety.confidence,'LOW');
const formattingSource={monitoring:{authorityTier:'primary',topics:['permit']}};
assert.equal(classifyChange(formattingSource,{changed:true,added:['Unrelated office hours'],removed:[]}),'C_INFORMATIONAL_IRRELEVANT_TO_HPP');
assert.deepEqual(safetyAssessment(formattingSource,'F_CLEAR_REGULATORY_CHANGE',{ruleIds:['project.building']}).decision,'HUMAN_REVIEW');
console.log('fixture scenarios: no-change, formatting/irrelevant, regulatory, safety gate');
console.log('monitor tests: PASS');
